#!/bin/bash
# BYPASS DOCKER - DIRECT NGINX DEPLOYMENT
# Since Docker keeps serving old version, let's deploy directly to nginx

echo "🚀 BYPASSING DOCKER - DIRECT DEPLOYMENT"
echo "======================================="
echo ""

echo "❌ PROBLEM: Docker keeps serving old cached version"
echo "✅ SOLUTION: Deploy optimized build directly to nginx"
echo ""

echo "RUN THESE COMMANDS ON YOUR VPS:"
echo "==============================="
echo ""

echo "# 1. Stop Docker containers (they're not working anyway)"
echo "docker-compose -f docker-compose.prod.yml down"
echo ""

echo "# 2. Install nginx directly (if not already installed)"
echo "sudo apt update"
echo "sudo apt install nginx -y"
echo ""

echo "# 3. Pull latest code with optimizations"
echo "git pull origin main"
echo ""

echo "# 4. Build optimized frontend locally on VPS"
echo "cd frontend"
echo "npm install --legacy-peer-deps"
echo "npm run build"
echo "cd .."
echo ""

echo "# 5. Deploy build directly to nginx"
echo "sudo rm -rf /var/www/html/*"
echo "sudo cp -r frontend/build/* /var/www/html/"
echo "sudo chown -R www-data:www-data /var/www/html"
echo ""

echo "# 6. Configure nginx for React app"
echo "sudo tee /etc/nginx/sites-available/codementee > /dev/null << 'EOF'"
echo "server {"
echo "    listen 80;"
echo "    server_name codementee.io www.codementee.io;"
echo "    return 301 https://\$server_name\$request_uri;"
echo "}"
echo ""
echo "server {"
echo "    listen 443 ssl http2;"
echo "    server_name codementee.io www.codementee.io;"
echo ""
echo "    # SSL configuration (use your existing certificates)"
echo "    ssl_certificate /etc/letsencrypt/live/codementee.io/fullchain.pem;"
echo "    ssl_certificate_key /etc/letsencrypt/live/codementee.io/privkey.pem;"
echo ""
echo "    # Frontend"
echo "    location / {"
echo "        root /var/www/html;"
echo "        index index.html;"
echo "        try_files \$uri \$uri/ /index.html;"
echo "        "
echo "        # Cache static assets"
echo "        location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg)$ {"
echo "            expires 1y;"
echo "            add_header Cache-Control \"public, immutable\";"
echo "        }"
echo "    }"
echo ""
echo "    # Backend API (keep Docker backend running)"
echo "    location /api/ {"
echo "        proxy_pass http://127.0.0.1:8001;"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
echo "    }"
echo "}"
echo "EOF"
echo ""

echo "# 7. Enable the site"
echo "sudo ln -sf /etc/nginx/sites-available/codementee /etc/nginx/sites-enabled/"
echo "sudo rm -f /etc/nginx/sites-enabled/default"
echo ""

echo "# 8. Test and reload nginx"
echo "sudo nginx -t"
echo "sudo systemctl reload nginx"
echo ""

echo "# 9. Start only the backend container (for API)"
echo "docker-compose -f docker-compose.prod.yml up -d backend"
echo ""

echo "# 10. Test the deployment"
echo "sleep 10"
echo "curl -s https://codementee.io | grep -o \"main\\.[^\\\"]*\\.js\""
echo "# Should show: main.b73ac925.js"
echo ""

echo "🎯 EXPECTED RESULTS:"
echo "- Frontend served directly by nginx (fast)"
echo "- Backend API still via Docker (working)"
echo "- New JS bundle: main.b73ac925.js"
echo "- Website loads in <1 second"
echo ""

echo "📋 WHY THIS WORKS:"
echo "- Bypasses Docker frontend caching issues"
echo "- Uses optimized build with PostHog removed"
echo "- Direct nginx serving (fastest possible)"
echo "- Keeps backend API working via Docker"