#!/bin/bash

echo "🚀 Complete Codementee.io Deployment Guide"
echo "=========================================="
echo ""

echo "📋 Step 1: Pull latest changes and fix frontend build (as codementee user)"
echo "--------------------------------------------------------------------------"
echo "su - codementee"
echo "cd /var/www/codementee"
echo "git pull origin main"
echo "chmod +x *.sh"
echo "./fix-frontend-build.sh"
echo ""

echo "📋 Step 2: Configure Nginx (as root user)"
echo "------------------------------------------"
echo "su -"
echo "cd /var/www/codementee"
echo "./configure-nginx-as-root.sh"
echo ""

echo "📋 Step 3: Start Docker containers (as codementee user)"
echo "-------------------------------------------------------"
echo "su - codementee"
echo "cd /var/www/codementee"
echo "docker-compose -f docker-compose.prod.yml down"
echo "docker-compose -f docker-compose.prod.yml up -d"
echo ""

echo "📋 Step 4: Verify everything is working"
echo "---------------------------------------"
echo "# Check container status:"
echo "docker-compose -f docker-compose.prod.yml ps"
echo ""
echo "# Test local connections:"
echo "curl http://localhost:3000  # Frontend"
echo "curl http://localhost:8001/health  # Backend"
echo ""
echo "# Test domain:"
echo "curl http://codementee.io"
echo ""

echo "🎯 Expected Result:"
echo "- Frontend container running on port 3000"
echo "- Backend container running on port 8001"
echo "- Nginx proxying codementee.io to localhost:3000"
echo "- API calls to codementee.io/api/* proxied to localhost:8001"
echo ""

echo "🌍 Your site will be live at: http://codementee.io"